version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: botocore
    versions:
    - 1.19.62
    - 1.19.63
    - 1.20.0
    - 1.20.1
    - 1.20.10
    - 1.20.11
    - 1.20.12
    - 1.20.13
    - 1.20.14
    - 1.20.15
    - 1.20.16
    - 1.20.17
    - 1.20.18
    - 1.20.19
    - 1.20.2
    - 1.20.20
    - 1.20.21
    - 1.20.22
    - 1.20.23
    - 1.20.24
    - 1.20.25
    - 1.20.26
    - 1.20.27
    - 1.20.29
    - 1.20.3
    - 1.20.30
    - 1.20.32
    - 1.20.33
    - 1.20.34
    - 1.20.35
    - 1.20.36
    - 1.20.38
    - 1.20.39
    - 1.20.4
    - 1.20.40
    - 1.20.41
    - 1.20.43
    - 1.20.44
    - 1.20.45
    - 1.20.46
    - 1.20.47
    - 1.20.48
    - 1.20.49
    - 1.20.5
    - 1.20.50
    - 1.20.51
    - 1.20.52
    - 1.20.53
    - 1.20.54
    - 1.20.55
    - 1.20.56
    - 1.20.57
    - 1.20.58
    - 1.20.59
    - 1.20.6
    - 1.20.7
    - 1.20.8
    - 1.20.9
  - dependency-name: black
    versions:
    - 20.8b1
    - 21.4b0
    - 21.4b1
  - dependency-name: s3transfer
    versions:
    - 0.3.4
    - 0.3.6
    - 0.3.7
    - 0.4.0
    - 0.4.1
  - dependency-name: astroid
    versions:
    - 2.4.2
    - "2.5"
    - 2.5.1
    - 2.5.2
    - 2.5.3
  - dependency-name: pyflakes
    versions:
    - 2.2.0
    - 2.3.0
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: isort
    versions:
    - 5.7.0
  - dependency-name: rope
    versions:
    - 0.18.0
