# Generated by Django 2.2.1 on 2019-10-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todonow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='message',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
