# Generated by Django 2.2.6 on 2019-11-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todonow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='confirm_complete',
            field=models.BooleanField(default=False),
        ),
    ]
