# Generated by Django 2.2.1 on 2019-10-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todonow', '0002_todo_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='message',
        ),
    ]
