# Generated by Django 2.2.6 on 2019-11-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todonow', '0005_auto_20191104_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
